notifications:
  recipients:
    - activeldap@ml.commit-email.info

dist: xenial

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

matrix:
  include:
    - name: "2.4 & ActiveModel 4"
      rvm: 2.4
      gemfile: Gemfile.activemodel4
    - name: "2.4 & ActiveModel 5"
      rvm: 2.4
      gemfile: Gemfile.activemodel5
    - name: "2.5 & ActiveModel 4"
      rvm: 2.5
      gemfile: Gemfile.activemodel4
    - name: "2.5 & ActiveModel 5"
      rvm: 2.5
      gemfile: Gemfile.activemodel5
    - name: "2.6 & ActiveModel 5"
      rvm: 2.6
      gemfile: Gemfile.activemodel5
    - name: "JRuby 9.2 & ActiveModel 5"
      jdk: openjdk8
      rvm: jruby-9.2.11.1
      gemfile: Gemfile.activemodel5

before_script:
  - password="secret"
  - encrypted_password=$(slappasswd -s ${password})
  - |
    (echo "version: 1";
     echo "dn: olcDatabase={1}mdb,cn=config";
     echo "changetype: modify";
     echo "replace: olcRootPW";
     echo "olcRootPW: ${encrypted_password}";
     echo "-") | sudo ldapmodify -Y EXTERNAL -H ldapi:///
  - sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f test/add-phonetic-attribute-options-to-slapd.ldif
  - base="dc=$(echo get slapd/domain | sudo debconf-communicate slapd | sed -e 's/^0 //' | sed -e 's/^\.//; s/\./,dc=/g')"
  - |
    (echo "test:";
     echo "  host: 127.0.0.1";
     echo "  base: dc=test,${base}";
     echo "  bind_dn: cn=admin,${base}";
     echo "  password: ${password}") > test/config.yaml
